import redis
from jito_py_rpc import JitoJsonRpcSDK

# Database
DB_CONFIG = {
    'database': 'YOUR_DB_NAME',
    'user': 'YOUR_DB_USER',
    'password': 'YOUR_DB_PASSWORD',
    'host': 'localhost',
    'port': 5432
}

# Redis
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIDS_DB = 1
redis_client = redis.StrictRedis(host=REDIS_HOST, port=REDIS_PORT, db=REDIDS_DB, decode_responses=False)

# Solana configuration
RPC_ENDPOINT = "YOUR_SOLANA_RPC_ENDPOINT"
RPC_ENDPOINT_BACKUP = "YOUR_SOLANA_RPC_ENDPOINT_BACKUP"
RPC_ENDPOINT_LIST = [
    "YOUR_SOLANA_RPC_ENDPOINT",
    "YOUR_SOLANA_RPC_ENDPOINT_EXTRA_1", 
    "YOUR_SOLANA_RPC_ENDPOINT_EXTRA_2", 
    ]
RPC_ENDPOINT_LIST_ID = 0

KEYPAIR_PATH = "/home/user/wallets/jito-access.json"

BLOCK_ENGINE_URL = "ny.mainnet.block-engine.jito.wtf"
jitoSdk = JitoJsonRpcSDK(url="https://ny.mainnet.block-engine.jito.wtf/api/v1")
JITO_TIP_ADDRESS = "HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe"
USE_JITO = True

# Keys
VAULT_PUBLIC_KEY = "YOUR_SOLANA_VAULT_PUBKEY"
VAULT_PRIVATE_KEY = "YOUR_SOLANA_VAULT_PRIVKEY"
PAYER_PUBLIC_KEY = "YOUR_SOLANA_PAYER_PUBKEY"
PAYER_PRIVATE_KEY = "YOUR_SOLANA_PAYER_PRIVKEY"
OPERATOR_PUBLIC_KEY = "YOUR_SOLANA_OPERATOR_PUBKEY"
OPERATOR_PRIVATE_KEY = "YOUR_SOLANA_OPERATOR_PRIVKEY"

# Address Lookup Table
TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
SOLANA_PROGRAM = "So11111111111111111111111111111111111111112"
SYSVARRENT_PROGRAM = "SysvarRent111111111111111111111111111111111"
RAYDIUM_AMM_PROGRAM = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
METEORA_DLMM_PROGRAM = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
SERUM_OPENBOOK_PROGRAM = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"

# Associate Token Accounts
OPERATOR_WSOL_ATA = "YOUR_SOLANA_OPERATOR_WSOL_ATA"
VAULT_WSOL_ATA = "YOUR_SOLANA_VAULT_WSOL_ATA"

# WSOL_ATA_SEED = "YOUR_SOLANA_VAULT_WSOL_ATA_SEED"
# OPERATOR_WSOL_ATA_SEEDED = "YOUR_SOLANA_VAULT_WSOL_ATA_SEEDED"

# Connections
RPC_STATUS = "confirmed"
WS_RPC_STATUS = "processed"

# Trade
VAULT_BALANCE = 0.5
MIN_PROFIT = 0.000001
MIN_TRADE_SIZE = 0.01
MAX_PRICE_DIFF_PERCENTAGE = 99
UNIT_BUDGET =  1_000_000
UNIT_PRICE =  1_000_000

# Performance
MIN_METEORA_FEE = 2
METEORA_BINS_LEFT = 2
METEORA_BINS_RIGHT = 2
METEORA_BINS_TO_TRADE = 2

RESERVES_METEORA = 'redis' # 'rpc' | 'redis'
RESERVES_RAYDIUM = 'cache' # 'cache' | 'rpc' | 'redis'
RESERVES_MAX_SECONDS = 200 # Max ws receive delay

WS_MAX_SECONDS = 200 # Max ws receive delay